# # encoding: utf-8 # -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = 'generic/arch'

# Memorable name for your
VM_NAME = 'arch'

# VM User — 'vagrant' by default
VM_USER = 'vagrant'

# Username on your Mac
MAC_USER = 'danyeaw'

# Host folder to sync
HOST_PATH = '/Users/' + MAC_USER + '/Projects/vagrant-dev-toga/' + VM_NAME

# Where to sync to on Guest — 'vagrant' is the default user name
GUEST_PATH = '/home/' + VM_USER + '/Projects/vagrant-dev-toga/' + VM_NAME

# # VM Port — uncomment this to use NAT instead of DHCP
# VM_PORT = 8080

Vagrant.configure(2) do |config|

  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX

  # Actual machine name
  config.vm.hostname = VM_NAME

  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
    v.gui = true
  end

  #DHCP — comment this out if planning on using NAT instead
  config.vm.network "private_network", ip: "172.28.128.10" 

  # # Port forwarding — uncomment this to use NAT instead of DHCP
  # config.vm.network "forwarded_port", guest: 80, host: VM_PORT

  # Sync folder
  config.vm.synced_folder HOST_PATH, GUEST_PATH, nfs: true

  # Disable default Vagrant folder, use a unique path per project
  config.vm.synced_folder '.', '/home/'+VM_USER+'', disabled: true

  config.vm.provision "shell", inline: <<-SHELL, privileged: false
    sudo pacman -Syu --noconfirm
    echo "Enable GUI"
    sudo pacman -R --noconfirm virtualbox-guest-utils-nox
    sudo pacman -S --noconfirm xorg-server xorg-xinit xorg-apps xfce4 \
      virtualbox-guest-dkms virtualbox-guest-utils
    echo 'exec startxfce4' >> ~/.xinitrc
    echo "Install pygobject and cairo locally"
    sudo pacman -S --noconfirm python-gobject python2-gobject gtk3 \
      gobject-intropection
    # echo "Install build dependencies for pygobject"
    # sudo pacman -S base-devel
    echo "Install python virtualenv and wheel"
    sudo pacman -S --noconfirm python-virtualenv python-wheel
    echo "Install dependencies for pyenv" 
    sudo pacman -S --noconfirm base-devel openssl zlib git
    # Install pyenv
    echo "Install pyenv"
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc
    echo "Setup python 3.6.4"
    ~/.pyenv/bin/pyenv install 3.6.4
    # Install pipsi
    echo "Install pipsi"
    curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3 - --src=git+https://github.com/mitsuhiko/pipsi.git\#egg=pipsi
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
    echo "Install pipenv"
    ~/.local/bin/pipsi install pew
    ~/.local/bin/pipsi install pipenv
    echo "Start VBoxClient"
    sudo VBoxClient --clipboard
    sudo VBoxClient --draganddrop
    sudo VBoxClient --display
    sudo VBoxClient --checkhostversion
    sudo VBoxClient --seamless
    echo "All set, run startx to launch your GUI"
  SHELL
end
