# # encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = 'fedora/27-cloud-base'

# Memorable name for your
VM_NAME = 'fedora'

# VM User — 'vagrant' by default
VM_USER = 'vagrant'

# Username on your Mac
MAC_USER = 'danyeaw'

# Host folder to sync
HOST_PATH = '/Users/' + MAC_USER + '/Projects/vagrant-dev-toga/' + VM_NAME

# Where to sync to on Guest — 'vagrant' is the default user name
GUEST_PATH = '/home/' + VM_USER + '/Projects/vagrant-dev-toga/' + VM_NAME

# # VM Port — uncomment this to use NAT instead of DHCP
# VM_PORT = 8080

Vagrant.configure(2) do |config|

  # Vagrant box from Fedora
  config.vm.box = VAGRANT_BOX

  config.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-Vagrant-27-1.6.x86_64.vagrant-virtualbox.box"

  # Actual machine name
  config.vm.hostname = VM_NAME

  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
    v.gui = true
  end

  #DHCP — comment this out if planning on using NAT instead
  config.vm.network "private_network", ip: "172.28.128.10" 

  # # Port forwarding — uncomment this to use NAT instead of DHCP
  # config.vm.network "forwarded_port", guest: 80, host: VM_PORT

  # Sync folder, enable NFS for performance
  config.vm.synced_folder HOST_PATH, GUEST_PATH, nfs: true

  # Disable default Vagrant folder, use a unique path per project
  config.vm.synced_folder '.', '/home/'+VM_USER+'', disabled: true

  config.vm.provision "shell", inline: <<-SHELL, privileged: false
    echo "Enable GUI"
    sudo dnf update -y
    sudo dnf install -y @xfce-desktop-environment elfutils-libelf-devel \
      libXmu kernel-devel 
    echo 'exec startxfce4' >> ~/.xinitrc
    echo "Install pygobject and cairo locally"
    sudo dnf install -y pygobject3 python3-gobject gtk3 
    echo "Install build dependencies for pygobject"
    sudo dnf install -y python3-cairo-devel cairo-gobject-devel \ 
      gobject-introspection-devel
    echo "Install python virtualenv and wheel"
    sudo dnf install -y python-virtualenv python-wheel
    echo "Install dependencies for pyenv" 
    sudo dnf install -y gcc zlib-devel bzip2 bzip2-devel readline-devel \
      sqlite sqlite-devel openssl-devel tk-devel git
    # Install pyenv
    echo "Install pyenv"
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc
    echo "Setup python 3.6.4"
    ~/.pyenv/bin/pyenv install 3.6.4
    # Install pipsi
    echo "Install pipsi"
    curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3 - --src=git+https://github.com/mitsuhiko/pipsi.git\#egg=pipsi
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
    echo "Install pipenv"
    ~/.local/bin/pipsi install pew
    ~/.local/bin/pipsi install pipenv
    echo "Start VBoxClient"
    sudo VBoxClient --clipboard
    sudo VBoxClient --draganddrop
    sudo VBoxClient --display
    sudo VBoxClient --checkhostversion
    sudo VBoxClient --seamless
    echo "All set, run startxfce4& to launch your GUI"
  SHELL
end
